### ISSUE TITLE
Uncaught Error: findDOMNode was called on an unmounted component.

### ISSUE THREAD

**Issue by arosenthal-r7** [planttheidea/react-windowed-list#7]
As we talked about, it looks like somehow windowed list is trying to call `updateScrollParent` before being mounted... 

<img width="890" alt="screen shot 2017-06-22 at 2 46 51 pm" src="https://user-images.githubusercontent.com/21044316/27450553-0a134648-575a-11e7-87fb-6042b9e27946.png">

you know where to find me if you need more details...

**Comment by planttheidea** [comment]
I just published `1.4.1` which no longer tries to call `findDOMNode` except on mount and when the renderContainer is established (which is once) ... it was making a bunch of calls at runtime before, and instead I'm just storing the DOM elements as instance values so I don't need to requery them. This should solve the issue (and potentially improve performance), but lemme know since it is tough to find a way to reproduce this error.

**Comment by arosenthal-r7** [comment]
Word
